'''
DISCLAIMER: THIS SCRIPT WAS ALMOST ENTIRELY GENERATED BY CHATGPT

overpass_places.py

Query OpenStreetMap populated places through the Overpass API.

The public interface is the single function:

    query_places()

The function returns a pandas.DataFrame containing point locations and
selected OSM metadata.

Optionally, administrative metadata can be attached to each place. The
administrative divisions are returned as descriptive attributes only;
administrative boundary geometry is NEVER downloaded.

Supported place types:

    city
    town
    village
    hamlet

Default:

    city + town

Supported output formats, inferred from filename:

    .csv
    .xlsx
    .xls
    .geojson
    .json
    .shp

The canonical in-memory return value is always a pandas.DataFrame.

For GeoJSON and Shapefile output, point geometry is constructed from
longitude/latitude at the final output stage.

Dependencies:

    requests
    pandas

Optional dependencies for geospatial output:

    geopandas
    shapely
    fiona

Optional dependency for Excel output:

    openpyxl


========================================================================
BASIC USAGE
========================================================================

Import the function:

    from overpass_places import query_places


1. Query cities and towns
-------------------------

The default behavior returns cities and towns within the bounding box.

    places = query_places(
        bbox=(
            37.0,     # south
            -123.0,   # west
            42.0,     # north
            -119.0,   # east
        )
    )

The returned object is a pandas.DataFrame.


2. Query only cities
--------------------

    cities = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        place_types=("city",),
    )


3. Query villages and hamlets
-----------------------------

    small_places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        place_types=(
            "village",
            "hamlet",
        ),
    )


4. Query all four place types
-----------------------------

    all_places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        place_types=(
            "city",
            "town",
            "village",
            "hamlet",
        ),
    )


========================================================================
NAME LANGUAGES
========================================================================

OpenStreetMap normally stores the local/default place name in:

    name

Additional languages are commonly stored as:

    name:en
    name:es
    name:fr
    name:de
    name:zh
    name:ja

and so forth.

The function can use these language-specific tags without making
additional Overpass requests.


5. Use the local/default name
-----------------------------

This is the default behavior.

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        )
    )

The main name column is taken from:

    name


6. Request one language
-----------------------

For example, request English names:

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        name_languages="en",
    )

The main "name" column will contain the English OSM name
(name:en) when available.

If English is not available for a particular place, the local
"name" value is used for that row.

If name:en is completely absent from the entire result set, a warning
is issued and the local/default names are used.


7. Request multiple languages
-----------------------------

Multiple languages can be requested:

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        name_languages=(
            "en",
            "es",
            "fr",
        ),
    )

The returned DataFrame will contain:

    name
    name_en
    name_es
    name_fr

The language-specific columns contain the corresponding OSM
language-specific names when available.

The main "name" column uses the first requested language available
for each individual place.

For example, with:

    name_languages=("en", "fr", "de")

a place with only:

    name:fr

will use its French name as "name".

A place with:

    name:de

but no English or French name will use its German name.

If none of the requested language names exist for a place, the local
"name" value is used.


8. Missing languages
--------------------

If a requested language is completely absent from the returned data,
the function issues a warning.

For example:

    places = query_places(
        bbox=(37.0, -123.0, 42.0, -119.0),
        name_languages=("en", "xx"),
    )

If no name:xx tags exist, a warning similar to the following is
generated:

    Requested language 'xx' is not available in the returned
    OSM data. Available language tags: en, es, fr, de

The available languages are determined from the actual OSM tags
returned by Overpass.

The unavailable language column is still created, but its values will
be missing.


9. Language fallback
--------------------

Language selection is performed independently for every place.

For:

    name_languages=("en", "es", "fr")

the selection priority is:

    1. name:en
    2. name:es
    3. name:fr
    4. name

Thus the function does not discard a place merely because its preferred
language is unavailable.


========================================================================
ADMINISTRATIVE METADATA
========================================================================

10. Include administrative divisions
-------------------------------------

Set include_admin=True to attach administrative information to each
place.

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        include_admin=True,
    )

Additional columns can include:

    country
    admin_level_2
    admin_level_3
    admin_level_4
    admin_level_5
    admin_level_6
    admin_level_7
    admin_level_8
    administrative_divisions

Administrative boundary geometry is NOT downloaded.

The administrative information is descriptive metadata associated
with each place point.


11. Retrieve selected administrative levels
--------------------------------------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        include_admin=True,
        admin_levels=(
            2,
            4,
            6,
        ),
    )


========================================================================
FILE OUTPUT
========================================================================

12. Write CSV
-------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        output="places.csv",
    )


13. Write Excel
---------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        output="places.xlsx",
    )


14. Write GeoJSON
-----------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        output="places.geojson",
    )

GeoJSON contains POINT geometries constructed from longitude and
latitude.


15. Write ESRI Shapefile
------------------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        output="places.shp",
    )

The output format is inferred from the extension.

If output=None, no file is written.


========================================================================
CUSTOM OVERPASS QUERIES
========================================================================

16. Use a custom Overpass query
--------------------------------

A custom query can be supplied through the query parameter.

The query must contain:

    {bbox}

For example:

    custom_query = """
    [out:json][timeout:60];

    node
      ["place"="city"]
      ({bbox});

    out body;
    """

    cities = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        query=custom_query,
    )


17. Custom query with language selection
-----------------------------------------

Language handling occurs after the Overpass response is received, so
custom queries normally do not need to do anything special for
language support.

For example:

    custom_query = """
    [out:json][timeout:60];

    node
      ["place"~"^(city|town)$"]
      ({bbox});

    out body;
    """

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        query=custom_query,
        name_languages=("en", "fr"),
    )

The OSM node's name, name:en, name:fr, etc. tags are returned by
"out body" and processed by the Python code.


========================================================================
LARGE-AREA QUERIES
========================================================================

18. Query a large geographic area
----------------------------------

Large bounding boxes are automatically subdivided when necessary.

For example:

    places = query_places(
        bbox=(
            30.0,
            -125.0,
            49.0,
            -66.0,
        )
    )

A large request is not necessarily sent to Overpass as one enormous
query.

The function recursively subdivides large or problematic tiles and
deduplicates the resulting OSM nodes using:

    osm_type + osm_id


========================================================================
CACHING
========================================================================

19. Default SQLite cache
------------------------

Caching is enabled by default.

The default cache location is:

    ~/.cache/overpass_places/cache.sqlite


20. Disable caching
-------------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        cache_path=None,
    )


21. Custom cache
----------------

    places = query_places(
        bbox=(
            37.0,
            -123.0,
            42.0,
            -119.0,
        ),
        cache_path="/path/to/cache.sqlite",
    )


========================================================================
TUNING LARGE REQUESTS
========================================================================

22. Reduce the maximum results per tile
---------------------------------------

    places = query_places(
        bbox=(
            30.0,
            -125.0,
            49.0,
            -66.0,
        ),
        max_results_per_tile=500,
    )


23. Increase subdivision depth
------------------------------

    places = query_places(
        bbox=(
            30.0,
            -125.0,
            49.0,
            -66.0,
        ),
        max_depth=10,
    )


========================================================================
RETURN VALUE
========================================================================

query_places() always returns a pandas.DataFrame.

Typical columns include:

    osm_id
    osm_type
    name
    place
    population
    latitude
    longitude
    wikidata
    wikipedia
    tags

When name_languages is specified, additional columns are created:

    name_en
    name_es
    name_fr

etc.

When include_admin=True, additional administrative columns are
returned.

The "tags" column retains the complete dictionary of OSM tags returned
by Overpass, except for the temporary internal "admin_info" tag.


========================================================================
DESIGN NOTES
========================================================================

This module intentionally treats populated places as POINT FEATURES.

Administrative information is used only as descriptive metadata.

The module does NOT:

    * download administrative boundary polygons
    * download multipolygon geometry
    * construct administrative polygons
    * perform point-in-polygon operations
    * spatially join places to administrative polygons

This keeps the returned dataset lightweight and appropriate for
applications whose primary data product is a table of populated-place
locations.


========================================================================
IMPLEMENTATION
========================================================================
'''

from __future__ import annotations

import hashlib
import json
import logging
import random
import re
import sqlite3
import time

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Optional

import pandas as pd
import requests


# ============================================================================
# Configuration
# ============================================================================

DEFAULT_SERVERS = (
    "https://overpass-api.de/api/interpreter",
    "https://overpass.private.coffee/api/interpreter",
)

DEFAULT_PLACE_TYPES = (
    "city",
    "town",
)

VALID_PLACE_TYPES = frozenset(
    {
        "city",
        "town",
        "village",
        "hamlet",
    }
)

DEFAULT_TIMEOUT = 90

DEFAULT_REQUEST_DELAY = 1.0

OVERPASS_THROTTLE_DELAY = 30.0

DEFAULT_MAX_RESULTS_PER_TILE = 1000

DEFAULT_MAX_DEPTH = 8

DEFAULT_RETRIES_PER_SERVER = 2

DEFAULT_ADMIN_LEVELS = (
    2,
    3,
    4,
    5,
    6,
    7,
    8,
)

DEFAULT_CACHE_PATH = (
    "~/.cache/overpass_places/cache.sqlite"
)


# ============================================================================
# Logging
# ============================================================================

logger = logging.getLogger(__name__)


# ============================================================================
# Bounding box
# ============================================================================

@dataclass(frozen=True)
class BBox:
    """
    Geographic bounding box.

    Coordinate order:

        south, west, north, east
    """

    south: float
    west: float
    north: float
    east: float

    def __post_init__(self):

        if not -90.0 <= self.south <= 90.0:
            raise ValueError(
                "south must be between -90 and 90."
            )

        if not -90.0 <= self.north <= 90.0:
            raise ValueError(
                "north must be between -90 and 90."
            )

        if not -180.0 <= self.west <= 180.0:
            raise ValueError(
                "west must be between -180 and 180."
            )

        if not -180.0 <= self.east <= 180.0:
            raise ValueError(
                "east must be between -180 and 180."
            )

        if self.south >= self.north:
            raise ValueError(
                "south must be less than north."
            )

        if self.west >= self.east:
            raise ValueError(
                "west must be less than east."
            )

    @classmethod
    def from_tuple(
        cls,
        bbox: Iterable[float],
    ) -> "BBox":

        values = tuple(bbox)

        if len(values) != 4:
            raise ValueError(
                "bbox must contain exactly four values in the form "
                "(south, west, north, east)."
            )

        return cls(
            south=float(values[0]),
            west=float(values[1]),
            north=float(values[2]),
            east=float(values[3]),
        )

    def as_overpass(self) -> str:

        return (
            f"{self.south:.7f},"
            f"{self.west:.7f},"
            f"{self.north:.7f},"
            f"{self.east:.7f}"
        )

    def split(
        self,
    ) -> tuple["BBox", "BBox", "BBox", "BBox"]:

        mid_lat = (
            self.south + self.north
        ) / 2.0

        mid_lon = (
            self.west + self.east
        ) / 2.0

        return (
            BBox(
                self.south,
                self.west,
                mid_lat,
                mid_lon,
            ),
            BBox(
                self.south,
                mid_lon,
                mid_lat,
                self.east,
            ),
            BBox(
                mid_lat,
                self.west,
                self.north,
                mid_lon,
            ),
            BBox(
                mid_lat,
                mid_lon,
                self.north,
                self.east,
            ),
        )


# ============================================================================
# Exceptions
# ============================================================================

class OverpassError(RuntimeError):
    """Base class for Overpass-related errors."""


class OverpassHTTPError(OverpassError):
    """Non-success HTTP response from Overpass."""

    def __init__(
        self,
        status_code: int,
        message: str,
        response_text: str = "",
    ):

        super().__init__(message)

        self.status_code = status_code
        self.response_text = response_text


class OverpassTemporaryError(OverpassError):
    """
    Error that may reasonably succeed if the query is retried or
    subdivided.
    """


# ============================================================================
# SQLite cache
# ============================================================================

class QueryCache:
    """
    Small SQLite cache for complete Overpass responses.
    """

    def __init__(
        self,
        path: Optional[str | Path],
    ):

        self.enabled = path is not None

        if not self.enabled:

            self.connection = None
            return

        self.path = (
            Path(path)
            .expanduser()
        )

        self.path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        self.connection = sqlite3.connect(
            str(self.path),
            timeout=30,
        )

        self.connection.execute(
            """
            CREATE TABLE IF NOT EXISTS overpass_cache (
                cache_key TEXT PRIMARY KEY,
                created_at REAL NOT NULL,
                response TEXT NOT NULL
            )
            """
        )

        self.connection.commit()

    def get(
        self,
        key: str,
    ) -> Optional[dict]:

        if not self.enabled:
            return None

        row = self.connection.execute(
            """
            SELECT response
            FROM overpass_cache
            WHERE cache_key = ?
            """,
            (key,),
        ).fetchone()

        if row is None:
            return None

        try:

            return json.loads(
                row[0]
            )

        except json.JSONDecodeError:

            logger.warning(
                "Ignoring invalid JSON in Overpass cache."
            )

            return None

    def put(
        self,
        key: str,
        response: dict,
    ) -> None:

        if not self.enabled:
            return

        self.connection.execute(
            """
            INSERT OR REPLACE INTO overpass_cache
            (
                cache_key,
                created_at,
                response
            )
            VALUES (?, ?, ?)
            """,
            (
                key,
                time.time(),
                json.dumps(response),
            ),
        )

        self.connection.commit()

    def close(self) -> None:

        if self.connection is not None:
            self.connection.close()


# ============================================================================
# Overpass HTTP client
# ============================================================================

class OverpassClient:

    def __init__(
        self,
        *,
        servers: Iterable[str],
        user_agent: str,
        timeout: int,
        request_delay: float,
        retries_per_server: int,
        cache: QueryCache,
    ):

        self.servers = tuple(
            server.rstrip("/")
            for server in servers
        )

        if not self.servers:

            raise ValueError(
                "At least one Overpass server is required."
            )

        self.user_agent = user_agent
        self.timeout = timeout

        self.request_delay = max(
            0.0,
            float(request_delay),
        )

        self.retries_per_server = max(
            1,
            int(retries_per_server),
        )

        self.cache = cache

        self.session = requests.Session()

        self.session.headers.update(
            {
                "User-Agent": user_agent,
                "Accept": "application/json",
                "Accept-Encoding": "gzip, deflate",
            }
        )

        self._last_request_time = 0.0

    @staticmethod
    def _cache_key(
        query: str,
        server: str,
    ) -> str:

        value = (
            server
            + "\n"
            + query
        )

        return hashlib.sha256(
            value.encode("utf-8")
        ).hexdigest()

    def _wait_for_rate_limit(self) -> None:

        elapsed = (
            time.monotonic()
            - self._last_request_time
        )

        remaining = (
            self.request_delay
            - elapsed
        )

        if remaining > 0:

            time.sleep(
                remaining
            )

    def execute(
        self,
        query: str,
    ) -> dict:

        last_error = None

        for server in self.servers:

            cache_key = (
                self._cache_key(
                    query,
                    server,
                )
            )

            cached = self.cache.get(
                cache_key
            )

            if cached is not None:

                logger.debug(
                    "Overpass cache hit."
                )

                return cached

            for attempt in range(
                1,
                self.retries_per_server + 1,
            ):

                try:

                    self._wait_for_rate_limit()

                    logger.debug(
                        "Overpass request to %s "
                        "(attempt %d/%d).",
                        server,
                        attempt,
                        self.retries_per_server,
                    )

                    self._last_request_time = (
                        time.monotonic()
                    )

                    response = self.session.post(
                        server,
                        data={
                            "data": query
                        },
                        timeout=self.timeout,
                    )

                    status = (
                        response.status_code
                    )

                    if status == 200:

                        try:

                            result = (
                                response.json()
                            )

                        except ValueError as exc:

                            raise OverpassError(
                                "Overpass returned HTTP 200 "
                                "but the response was not valid JSON."
                            ) from exc

                        self.cache.put(
                            cache_key,
                            result,
                        )

                        return result

                    if status in (
                        406,
                        429,
                    ):

                        last_error = (
                            OverpassHTTPError(
                                status,
                                (
                                    f"Overpass returned HTTP "
                                    f"{status} from {server}."
                                ),
                                response.text[:4000],
                            )
                        )

                        logger.warning(
                            "Overpass returned HTTP %d. "
                            "Waiting %.0f seconds.",
                            status,
                            OVERPASS_THROTTLE_DELAY,
                        )

                        time.sleep(
                            OVERPASS_THROTTLE_DELAY
                        )

                        continue

                    if status in (
                        500,
                        502,
                        503,
                        504,
                    ):

                        last_error = (
                            OverpassTemporaryError(
                                f"Temporary Overpass HTTP "
                                f"{status} error."
                            )
                        )

                        delay = min(
                            30.0,
                            2.0 ** attempt,
                        )

                        delay += random.uniform(
                            0.0,
                            1.0,
                        )

                        logger.warning(
                            "Overpass HTTP %d; "
                            "retrying in %.1f seconds.",
                            status,
                            delay,
                        )

                        time.sleep(
                            delay
                        )

                        continue

                    raise OverpassHTTPError(
                        status,
                        (
                            f"Overpass returned HTTP "
                            f"{status} from {server}."
                        ),
                        response.text[:4000],
                    )

                except requests.Timeout:

                    last_error = (
                        OverpassTemporaryError(
                            f"Timeout contacting {server}."
                        )
                    )

                    delay = min(
                        30.0,
                        2.0 ** attempt,
                    )

                    time.sleep(
                        delay
                    )

                except requests.ConnectionError as exc:

                    last_error = (
                        OverpassTemporaryError(
                            f"Connection error contacting "
                            f"{server}: {exc}"
                        )
                    )

                    delay = min(
                        30.0,
                        2.0 ** attempt,
                    )

                    time.sleep(
                        delay
                    )

                except OverpassHTTPError:

                    raise

        if last_error is not None:

            raise last_error

        raise OverpassError(
            "Overpass request failed."
        )


# ============================================================================
# Validation
# ============================================================================

def _normalize_place_types(
    place_types: Iterable[str],
) -> tuple[str, ...]:

    normalized = []

    for place_type in place_types:

        place_type = (
            str(place_type)
            .strip()
            .lower()
        )

        if place_type not in VALID_PLACE_TYPES:

            raise ValueError(
                f"Invalid place type '{place_type}'. "
                f"Valid values are: "
                f"{', '.join(sorted(VALID_PLACE_TYPES))}"
            )

        if place_type not in normalized:

            normalized.append(
                place_type
            )

    if not normalized:

        raise ValueError(
            "At least one place type must be selected."
        )

    return tuple(
        normalized
    )


def _normalize_admin_levels(
    admin_levels: Iterable[int],
) -> tuple[int, ...]:

    levels = sorted(
        {
            int(level)
            for level in admin_levels
        }
    )

    for level in levels:

        if not 1 <= level <= 15:

            raise ValueError(
                "Administrative levels must be "
                "between 1 and 15."
            )

    return tuple(levels)


def _normalize_name_languages(
    name_languages,
) -> Optional[tuple[str, ...]]:
    """
    Normalize requested OSM language codes.

    Returns None when the caller requested the local/default name.

    A single string is treated as one language rather than as an
    iterable of individual characters.
    """

    if name_languages is None:
        return None

    if isinstance(
        name_languages,
        str,
    ):

        name_languages = (
            name_languages,
        )

    normalized = []

    for language in name_languages:

        language = (
            str(language)
            .strip()
            .lower()
        )

        if not language:
            continue

        # OSM language keys normally consist of language codes and may
        # contain a region/script component such as pt-br or zh-hans.
        if not re.fullmatch(
            r"[a-z0-9]+(?:[-_][a-z0-9]+)*",
            language,
        ):

            raise ValueError(
                f"Invalid language code '{language}'."
            )

        if language not in normalized:

            normalized.append(
                language
            )

    if not normalized:

        raise ValueError(
            "name_languages must contain at least "
            "one language code."
        )

    return tuple(
        normalized
    )


# ============================================================================
# Default query
# ============================================================================

def _build_default_query(
    bbox: BBox,
    place_types: tuple[str, ...],
    include_admin: bool,
    admin_levels: tuple[int, ...],
    timeout: int,
) -> str:

    place_regex = "|".join(
        re.escape(place_type)
        for place_type in place_types
    )

    if not include_admin:

        return f"""
[out:json][timeout:{timeout}];

node
  ["place"~"^({place_regex})$"]
  ({bbox.as_overpass()});

out body;
""".strip()

    admin_regex = "|".join(
        str(level)
        for level in admin_levels
    )

    return f"""
[out:json][timeout:{timeout}];

node
  ["place"~"^({place_regex})$"]
  ({bbox.as_overpass()})
  ->.places;

foreach.places->.place
(
    .place is_in->.areas;

    area.areas
      [boundary="administrative"]
      [admin_level~"^({admin_regex})$"]
      [name]
      ->.admin;

    convert node ::=::,
        ::id = id(),
        admin_info = .admin.set(
            t["admin_level"] + "=" + t["name"]
        );

    out body;
);
""".strip()


# ============================================================================
# Custom query
# ============================================================================

def _replace_bbox(
    query: str,
    bbox: BBox,
) -> str:

    if "{bbox}" not in query:

        raise ValueError(
            "Custom queries must contain the literal "
            "'{bbox}' placeholder."
        )

    return query.replace(
        "{bbox}",
        bbox.as_overpass(),
    )


def _build_custom_query(
    query_template: str,
    bbox: BBox,
    include_admin: bool,
    admin_levels: tuple[int, ...],
    timeout: int,
) -> str:

    expanded = _replace_bbox(
        query_template,
        bbox,
    )

    if not include_admin:

        return expanded

    cleaned = re.sub(
        r"(?im)^\s*out(?:\s+[^;]*)?;\s*$",
        "",
        expanded,
    )

    admin_regex = "|".join(
        str(level)
        for level in admin_levels
    )

    return f"""
[out:json][timeout:{timeout}];

(
{cleaned}
)->.places;

foreach.places->.place
(
    .place is_in->.areas;

    area.areas
      [boundary="administrative"]
      [admin_level~"^({admin_regex})$"]
      [name]
      ->.admin;

    convert node ::=::,
        ::id = id(),
        admin_info = .admin.set(
            t["admin_level"] + "=" + t["name"]
        );

    out body;
);
""".strip()


# ============================================================================
# Population
# ============================================================================

def _parse_population(
    value,
) -> Optional[int]:

    if value is None:
        return None

    if isinstance(
        value,
        bool,
    ):
        return None

    if isinstance(
        value,
        int,
    ):
        return value

    text = str(value).strip()

    if not text:
        return None

    text = (
        text
        .replace(",", "")
        .replace(" ", "")
    )

    try:

        return int(
            float(text)
        )

    except (
        ValueError,
        TypeError,
    ):

        return None


# ============================================================================
# Administrative metadata
# ============================================================================

def _parse_admin_info(
    value,
) -> dict[int, str]:

    if value is None:

        return {}

    text = str(
        value
    ).strip()

    if not text:

        return {}

    result = {}

    for item in text.split(";"):

        item = item.strip()

        if not item:
            continue

        if "=" not in item:
            continue

        level_text, name = (
            item.split(
                "=",
                1,
            )
        )

        try:

            level = int(
                level_text.strip()
            )

        except ValueError:

            continue

        name = name.strip()

        if not name:
            continue

        if level not in result:

            result[level] = name

    return result


# ============================================================================
# Name/language helpers
# ============================================================================

def _language_tag_name(
    language: str,
) -> str:
    """
    Convert a language code into the corresponding OSM tag.

    Examples:

        en       -> name:en
        pt-br    -> name:pt-br
        zh_hans  -> name:zh_hans
    """

    return f"name:{language}"


def _extract_available_languages(
    tags: dict,
) -> set[str]:
    """
    Extract language-specific OSM name tags.

    Only tags whose keys are exactly of the form:

        name:<language>

    are considered.

    This deliberately excludes other name-related tags such as:

        name:official
        name:alt
        name:short
        name:etymology

    because those are not necessarily language identifiers.
    """

    languages = set()

    for key in tags:

        if not key.startswith(
            "name:"
        ):

            continue

        language = key[5:]

        if not language:
            continue

        if re.fullmatch(
            r"[a-z0-9]+(?:[-_][a-z0-9]+)*",
            language.lower(),
        ):

            languages.add(
                language.lower()
            )

    return languages


def _select_name(
    tags: dict,
    requested_languages: Optional[tuple[str, ...]],
) -> str | None:
    """
    Select the primary name for a place.

    If no languages were requested, use the local/default OSM name.

    If languages were requested, use the first available requested
    language. If none are available for that place, fall back to the
    local/default OSM name.
    """

    local_name = tags.get(
        "name"
    )

    if requested_languages is None:

        return local_name

    for language in requested_languages:

        value = tags.get(
            _language_tag_name(
                language
            )
        )

        if value is not None:

            value = str(
                value
            ).strip()

            if value:

                return value

    return local_name


# ============================================================================
# Parse place
# ============================================================================

def _parse_place(
    element: dict,
    include_admin: bool,
    admin_levels: tuple[int, ...],
    name_languages: Optional[tuple[str, ...]],
) -> dict:

    tags = dict(
        element.get(
            "tags",
            {},
        )
    )

    latitude = element.get(
        "lat"
    )

    longitude = element.get(
        "lon"
    )

    try:

        latitude = float(
            latitude
        )

    except (
        TypeError,
        ValueError,
    ):

        latitude = None

    try:

        longitude = float(
            longitude
        )

    except (
        TypeError,
        ValueError,
    ):

        longitude = None

    row = {
        "osm_id": element.get(
            "id"
        ),

        "osm_type": element.get(
            "type",
            "node",
        ),

        "name": _select_name(
            tags,
            name_languages,
        ),

        "place": tags.get(
            "place"
        ),

        "population": _parse_population(
            tags.get(
                "population"
            )
        ),

        "latitude": latitude,

        "longitude": longitude,

        "wikidata": tags.get(
            "wikidata"
        ),

        "wikipedia": tags.get(
            "wikipedia"
        ),
    }

    # Add explicitly requested language columns.
    if name_languages is not None:

        for language in name_languages:

            value = tags.get(
                _language_tag_name(
                    language
                )
            )

            if value is not None:

                value = str(
                    value
                ).strip()

                if not value:

                    value = None

            row[
                f"name_{language.replace('-', '_')}"
            ] = value

    if include_admin:

        admin_info = _parse_admin_info(
            tags.get(
                "admin_info"
            )
        )

        for level in admin_levels:

            row[
                f"admin_level_{level}"
            ] = admin_info.get(
                level
            )

        row["country"] = (
            admin_info.get(2)
        )

        row[
            "administrative_divisions"
        ] = {
            str(level): name
            for level, name
            in sorted(
                admin_info.items()
            )
            if level in admin_levels
        }

    tags.pop(
        "admin_info",
        None,
    )

    row["tags"] = tags

    return row


def _extract_places(
    response: dict,
    include_admin: bool,
    admin_levels: tuple[int, ...],
    name_languages: Optional[tuple[str, ...]],
) -> list[dict]:

    places = []

    for element in response.get(
        "elements",
        [],
    ):

        if element.get(
            "type"
        ) != "node":

            continue

        row = _parse_place(
            element,
            include_admin=include_admin,
            admin_levels=admin_levels,
            name_languages=name_languages,
        )

        if (
            row["latitude"] is None
            or row["longitude"] is None
        ):

            logger.warning(
                "Skipping OSM node %s because "
                "coordinates are missing.",
                row["osm_id"],
            )

            continue

        places.append(
            row
        )

    return places


def _deduplicate_places(
    places: Iterable[dict],
) -> list[dict]:

    unique = {}

    for place in places:

        key = (
            place.get(
                "osm_type"
            ),
            place.get(
                "osm_id"
            ),
        )

        unique[key] = place

    return list(
        unique.values()
    )


# ============================================================================
# Language availability warnings
# ============================================================================

def _warn_about_missing_languages(
    places: Iterable[dict],
    requested_languages: Optional[tuple[str, ...]],
) -> None:
    """
    Warn once for requested languages that are entirely absent from the
    returned dataset.

    This intentionally does NOT warn when a language is missing from an
    individual place but exists elsewhere in the result. Language
    coverage can legitimately vary from place to place, and warning
    for every such occurrence would make large queries extremely noisy.
    """

    if not requested_languages:

        return

    available_languages = set()

    for place in places:

        tags = place.get(
            "tags",
            {}
        )

        available_languages.update(
            _extract_available_languages(
                tags
            )
        )

    missing_languages = [
        language
        for language
        in requested_languages
        if language not in available_languages
    ]

    if not missing_languages:

        return

    available_text = (
        ", ".join(
            sorted(
                available_languages
            )
        )
        if available_languages
        else "(none)"
    )

    for language in missing_languages:

        logger.warning(
            "Requested language '%s' is not available "
            "in the returned OSM data. Available "
            "language tags: %s. The local/default "
            "'name' value will be used where no "
            "requested language is available.",
            language,
            available_text,
        )


# ============================================================================
# Adaptive querying
# ============================================================================

def _query_tile(
    *,
    client: OverpassClient,
    bbox: BBox,
    query_builder,
    include_admin: bool,
    admin_levels: tuple[int, ...],
    name_languages: Optional[tuple[str, ...]],
    max_results_per_tile: int,
    max_depth: int,
    depth: int,
) -> list[dict]:

    logger.info(
        "Querying bbox at depth %d: %s",
        depth,
        bbox.as_overpass(),
    )

    query = query_builder(
        bbox
    )

    try:

        response = client.execute(
            query
        )

        places = _extract_places(
            response,
            include_admin=include_admin,
            admin_levels=admin_levels,
            name_languages=name_languages,
        )

    except OverpassTemporaryError:

        if depth >= max_depth:

            raise

        logger.warning(
            "Temporary Overpass failure at depth %d. "
            "Subdividing bbox.",
            depth,
        )

        results = []

        for child_bbox in bbox.split():

            results.extend(
                _query_tile(
                    client=client,
                    bbox=child_bbox,
                    query_builder=query_builder,
                    include_admin=include_admin,
                    admin_levels=admin_levels,
                    name_languages=name_languages,
                    max_results_per_tile=max_results_per_tile,
                    max_depth=max_depth,
                    depth=depth + 1,
                )
            )

        return _deduplicate_places(
            results
        )

    if (
        len(places)
        <= max_results_per_tile
        or depth >= max_depth
    ):

        return places

    logger.info(
        "BBox returned %d places, exceeding "
        "max_results_per_tile=%d. Subdividing.",
        len(places),
        max_results_per_tile,
    )

    results = []

    for child_bbox in bbox.split():

        results.extend(
            _query_tile(
                client=client,
                bbox=child_bbox,
                query_builder=query_builder,
                include_admin=include_admin,
                admin_levels=admin_levels,
                name_languages=name_languages,
                max_results_per_tile=max_results_per_tile,
                max_depth=max_depth,
                depth=depth + 1,
            )
        )

    return _deduplicate_places(
        results
    )


# ============================================================================
# Output
# ============================================================================

def _output_type(
    output: str | Path,
) -> str:

    suffix = (
        Path(output)
        .suffix
        .lower()
    )

    if suffix in (
        ".geojson",
        ".json",
    ):
        return "geojson"

    if suffix in (
        ".xlsx",
        ".xls",
    ):
        return "excel"

    if suffix == ".csv":
        return "csv"

    if suffix == ".shp":
        return "shapefile"

    raise ValueError(
        f"Unsupported output extension '{suffix}'. "
        "Supported extensions are: "
        ".geojson, .json, .xlsx, .xls, .csv, .shp"
    )


def _write_point_geospatial_output(
    dataframe: pd.DataFrame,
    output: str | Path,
    output_type: str,
) -> None:

    try:

        import geopandas as gpd

        from shapely.geometry import Point

    except ImportError as exc:

        raise ImportError(
            "GeoJSON/Shapefile output requires "
            "geopandas and shapely."
        ) from exc

    output_path = (
        Path(output)
        .expanduser()
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    geometry = [
        Point(
            longitude,
            latitude,
        )
        for longitude, latitude
        in zip(
            dataframe["longitude"],
            dataframe["latitude"],
        )
    ]

    gdf = gpd.GeoDataFrame(
        dataframe.copy(),
        geometry=geometry,
        crs="EPSG:4326",
    )

    if output_type == "geojson":

        gdf.to_file(
            output_path,
            driver="GeoJSON",
            encoding="utf-8",
        )

        return

    if output_type == "shapefile":

        shapefile_df = gdf.copy()

        if (
            "administrative_divisions"
            in shapefile_df.columns
        ):

            shapefile_df[
                "admin_divisions"
            ] = shapefile_df[
                "administrative_divisions"
            ].map(
                lambda value: (
                    json.dumps(
                        value,
                        ensure_ascii=False,
                    )
                    if isinstance(
                        value,
                        dict,
                    )
                    else value
                )
            )

            shapefile_df.drop(
                columns=[
                    "administrative_divisions"
                ],
                inplace=True,
            )

        if "tags" in shapefile_df.columns:

            shapefile_df["osm_tags"] = (
                shapefile_df["tags"].map(
                    lambda value: (
                        json.dumps(
                            value,
                            ensure_ascii=False,
                        )
                        if isinstance(
                            value,
                            dict,
                        )
                        else value
                    )
                )
            )

            shapefile_df.drop(
                columns=[
                    "tags"
                ],
                inplace=True,
            )

        shapefile_df.to_file(
            output_path,
            driver="ESRI Shapefile",
            encoding="utf-8",
        )

        return

    raise ValueError(
        f"Unsupported geospatial output type: "
        f"{output_type}"
    )


def _write_tabular_output(
    dataframe: pd.DataFrame,
    output: str | Path,
    output_type: str,
) -> None:

    output_path = (
        Path(output)
        .expanduser()
    )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    df = dataframe.copy()

    for column in df.columns:

        if df[column].map(
            lambda value: isinstance(
                value,
                (
                    dict,
                    list,
                    tuple,
                ),
            )
        ).any():

            df[column] = (
                df[column].map(
                    lambda value: (
                        json.dumps(
                            value,
                            ensure_ascii=False,
                        )
                        if isinstance(
                            value,
                            (
                                dict,
                                list,
                                tuple,
                            ),
                        )
                        else value
                    )
                )
            )

    if output_type == "csv":

        df.to_csv(
            output_path,
            index=False,
        )

        return

    if output_type == "excel":

        df.to_excel(
            output_path,
            index=False,
        )

        return

    raise ValueError(
        f"Unsupported tabular output type: "
        f"{output_type}"
    )


def _write_output(
    dataframe: pd.DataFrame,
    output: str | Path,
) -> None:

    output_type = _output_type(
        output
    )

    if output_type in (
        "geojson",
        "shapefile",
    ):

        _write_point_geospatial_output(
            dataframe,
            output,
            output_type,
        )

    else:

        _write_tabular_output(
            dataframe,
            output,
            output_type,
        )


# ============================================================================
# Public API
# ============================================================================

def query_places(
    bbox: Iterable[float],
    *,
    place_types: Iterable[str] = DEFAULT_PLACE_TYPES,
    name_languages=None,
    include_admin: bool = False,
    query: Optional[str] = None,
    admin_levels: Iterable[int] = DEFAULT_ADMIN_LEVELS,
    output: Optional[str | Path] = None,
    user_agent: str = (
        "MyOverpassPlaceTool/1.0 "
        "(replace-with-your-contact-information)"
    ),
    servers: Iterable[str] = DEFAULT_SERVERS,
    timeout: int = DEFAULT_TIMEOUT,
    request_delay: float = DEFAULT_REQUEST_DELAY,
    retries_per_server: int = DEFAULT_RETRIES_PER_SERVER,
    cache_path: Optional[str | Path] = DEFAULT_CACHE_PATH,
    max_results_per_tile: int = DEFAULT_MAX_RESULTS_PER_TILE,
    max_depth: int = DEFAULT_MAX_DEPTH,
    log_level: int = logging.WARNING,
) -> pd.DataFrame:
    """
    Query cities, towns, villages, and/or hamlets from OpenStreetMap.

    Parameters
    ----------
    **bbox**: *iterable*;
        Bounding box in the form:

            (south, west, north, east)

    **place_types**: *iterable, str*;
        One or more of:

            city
            town
            village
            hamlet

        Default:

            ("city", "town")

    **name_languages**: *iterable, str*
        Optional language or languages for place names.

        None:
            Use the local/default OSM "name" tag.

        "en":
            Use the English "name:en" tag as the primary name.

        ("en", "fr", "de"):
            Create name_en, name_fr, and name_de columns.
            The primary "name" column uses the first requested
            language available for each individual place.

        If none of the requested languages are available for a place,
        the local/default "name" tag is used.

        If a requested language is completely absent from the
        returned dataset, a warning is issued.

    **include_admin**: *bool*;
        Include administrative division names.

        Administrative boundary geometry is not downloaded.

    **query**: *str*;
        Optional custom Overpass QL query.

        Must contain:

            {bbox}

    **admin_levels**: *iterable, str*;
        Administrative levels to retrieve when include_admin=True.

    **output**: *str*;
        Optional output filename. Format is inferred from its extension.

    **user_agent**: *str*;
        Application-specific HTTP User-Agent.

    **servers**: *iterable, str*
        Overpass API endpoints.

    **timeout**: *int*;
        HTTP timeout in seconds.

    **request_delay**: *float*;
        Minimum delay between requests.

    **retries_per_server**: *int*;
        Number of retry attempts for transient failures.

    **cache_path**: *str*;
        SQLite cache path. Set to None to disable caching.

    **max_results_per_tile**: *int*;
        Maximum places allowed in a tile before subdivision.

    **max_depth**: *int*;
        Maximum recursive subdivision depth.

    **log_level**: *int*;
        Python logging level.

    Returns
    -------
    pandas.DataFrame
        Point-based place data.
    """

    logging.basicConfig(
        level=log_level,
        format=(
            "%(asctime)s "
            "%(levelname)s "
            "%(name)s: "
            "%(message)s"
        ),
    )

    normalized_bbox = BBox.from_tuple(
        bbox
    )

    normalized_place_types = (
        _normalize_place_types(
            place_types
        )
    )

    normalized_name_languages = (
        _normalize_name_languages(
            name_languages
        )
    )

    normalized_admin_levels = (
        _normalize_admin_levels(
            admin_levels
        )
    )

    if include_admin and not normalized_admin_levels:

        raise ValueError(
            "admin_levels cannot be empty when "
            "include_admin=True."
        )

    if timeout <= 0:

        raise ValueError(
            "timeout must be greater than zero."
        )

    if max_results_per_tile <= 0:

        raise ValueError(
            "max_results_per_tile must be greater than zero."
        )

    if max_depth < 0:

        raise ValueError(
            "max_depth cannot be negative."
        )

    if query is None:

        def query_builder(
            current_bbox: BBox,
        ) -> str:

            return _build_default_query(
                bbox=current_bbox,
                place_types=normalized_place_types,
                include_admin=include_admin,
                admin_levels=normalized_admin_levels,
                timeout=timeout,
            )

    else:

        if "{bbox}" not in query:

            raise ValueError(
                "Custom query must contain '{bbox}'."
            )

        def query_builder(
            current_bbox: BBox,
        ) -> str:

            return _build_custom_query(
                query,
                bbox=current_bbox,
                include_admin=include_admin,
                admin_levels=normalized_admin_levels,
                timeout=timeout,
            )

    cache = QueryCache(
        cache_path
    )

    try:

        client = OverpassClient(
            servers=servers,
            user_agent=user_agent,
            timeout=timeout,
            request_delay=request_delay,
            retries_per_server=retries_per_server,
            cache=cache,
        )

        places = _query_tile(
            client=client,
            bbox=normalized_bbox,
            query_builder=query_builder,
            include_admin=include_admin,
            admin_levels=normalized_admin_levels,
            name_languages=normalized_name_languages,
            max_results_per_tile=max_results_per_tile,
            max_depth=max_depth,
            depth=0,
        )

        places = _deduplicate_places(
            places
        )

        # Warn about languages only after the complete result set has
        # been assembled. This is important for large-area queries
        # because different recursive tiles may contain different
        # language coverage.
        _warn_about_missing_languages(
            places,
            normalized_name_languages,
        )

        if places:

            dataframe = pd.DataFrame(
                places
            )

            sort_columns = [
                column
                for column in (
                    "name",
                    "place",
                    "osm_id",
                )
                if column in dataframe.columns
            ]

            if sort_columns:

                dataframe.sort_values(
                    by=sort_columns,
                    kind="stable",
                    inplace=True,
                )

            dataframe.reset_index(
                drop=True,
                inplace=True,
            )

        else:

            columns = [
                "osm_id",
                "osm_type",
                "name",
            ]

            if normalized_name_languages is not None:

                columns.extend(
                    [
                        f"name_{language.replace('-', '_')}"
                        for language
                        in normalized_name_languages
                    ]
                )

            columns.extend(
                [
                    "place",
                    "population",
                    "latitude",
                    "longitude",
                    "wikidata",
                    "wikipedia",
                    "tags",
                ]
            )

            if include_admin:

                columns.append(
                    "country"
                )

                columns.extend(
                    [
                        f"admin_level_{level}"
                        for level
                        in normalized_admin_levels
                    ]
                )

                columns.append(
                    "administrative_divisions"
                )

            dataframe = pd.DataFrame(
                columns=columns
            )

        if output is not None:

            _write_output(
                dataframe,
                output,
            )

        return dataframe

    finally:

        cache.close()


# ============================================================================
# End of module
# ============================================================================